name: Github Action Workflow PROD

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - build-prod
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-prod:
    uses: Devops-Grupo-8/shipping-service-example/.github/workflows/deploy-to-eks.yml@main
    with:
      CI_ENV: prod
      CONTENTFUL_ENVIRONMENT: 'prod'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_SHIPPING }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG_SHIPPING_PROD }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME_PROD }}
      ENV: prod